import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import AppChrome from "@/components/AppChrome";
import { PRODUCT_NAME } from "@/lib/branding";

const publicSans = localFont({
  src: "./fonts/public-sans-latin.woff2",
  weight: "100 900",
  variable: "--font-public-sans",
});

const caslonDisplay = localFont({
  src: "./fonts/libre-caslon-display-latin-400-normal.woff2",
  weight: "400",
  variable: "--font-caslon-display",
});

const caslonText = localFont({
  src: [
    { path: "./fonts/libre-caslon-text-latin-400-normal.woff2", weight: "400", style: "normal" },
    { path: "./fonts/libre-caslon-text-latin-400-italic.woff2", weight: "400", style: "italic" },
  ],
  variable: "--font-caslon-text",
});

const barlowCondensed = localFont({
  src: [
    { path: "./fonts/barlow-condensed-700-latin.woff2", weight: "700" },
    { path: "./fonts/barlow-condensed-800-latin.woff2", weight: "800" },
    { path: "./fonts/barlow-condensed-900-latin.woff2", weight: "900" },
  ],
  variable: "--font-barlow-condensed",
});

export const metadata: Metadata = {
  title: PRODUCT_NAME,
  description: "Pick your situation, get the safe starting move, and go run it.",
  // The web app manifest is generated by app/manifest.ts (served at
  // /manifest.webmanifest); Next injects the <link rel="manifest"> automatically.
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#07121d",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${publicSans.variable} ${caslonDisplay.variable} ${caslonText.variable} ${barlowCondensed.variable} h-full`}>
      <body className="min-h-full bg-background text-foreground font-[family-name:var(--font-public-sans)]">
        <a
          href="#main-content"
          className="fixed left-4 top-2 z-[200] -translate-y-[150%] rounded-inner bg-white px-3.5 py-2.5 text-sm font-bold text-primary-dark shadow-modal focus:translate-y-0"
        >
          Skip to main content
        </a>
        <div className="site-shell">
          <SiteHeader />
          <AppChrome />
          <main id="main-content" tabIndex={-1} className="page-content">{children}</main>
          <SiteFooter />
        </div>
      </body>
    </html>
  );
}
